export enum WorkloadType {
  AD = 'AD',
  ENTRA = 'ENTRA',
  EXCHANGE = 'EXCHANGE',
  SHAREPOINT = 'SHAREPOINT',
  FILESERVER = 'FILESERVER',
}

export enum RequestStatus {
  DRAFT = 'DRAFT',
  PENDING_SUBMISSION = 'PENDING_SUBMISSION',
  PENDING_APPROVAL_1 = 'PENDING_APPROVAL_1',
  PENDING_APPROVAL_2 = 'PENDING_APPROVAL_2',
  PENDING_APPROVAL_3 = 'PENDING_APPROVAL_3',
  APPROVED = 'APPROVED',
  EXECUTING = 'EXECUTING',
  GRANTED = 'GRANTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
  FAILED = 'FAILED',
  ROLLED_BACK = 'ROLLED_BACK',
  CANCELLED = 'CANCELLED',
  ESCALATED = 'ESCALATED',
}

export enum PermissionAction {
  ADD = 'ADD',
  REMOVE = 'REMOVE',
}

export enum PermissionType {
  // AD / Entra
  MEMBER = 'MEMBER',
  OWNER = 'OWNER',
  // Exchange
  FULL_ACCESS = 'FULL_ACCESS',
  SEND_AS = 'SEND_AS',
  SEND_ON_BEHALF = 'SEND_ON_BEHALF',
  DL_MEMBER = 'DL_MEMBER',
  // SharePoint
  READ = 'READ',
  CONTRIBUTE = 'CONTRIBUTE',
  EDIT = 'EDIT',
  FULL_CONTROL = 'FULL_CONTROL',
  DESIGN = 'DESIGN',
  // File Server
  SMB_READ = 'SMB_READ',
  SMB_CHANGE = 'SMB_CHANGE',
  SMB_FULL = 'SMB_FULL',
  NTFS_READ = 'NTFS_READ',
  NTFS_MODIFY = 'NTFS_MODIFY',
  NTFS_FULL = 'NTFS_FULL',
}

export enum ApprovalAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  REASSIGN = 'REASSIGN',
  ESCALATE = 'ESCALATE',
  TIMEOUT = 'TIMEOUT',
}

export enum ResourceSensitivity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum TierLevel {
  TIER1 = 1,
  TIER2 = 2,
  TIER3 = 3,
}

export enum PlatformRole {
  REQUESTER = 'requester',
  APPROVER = 'approver',
  POLICY_ADMIN = 'policy_admin',
  EXECUTOR = 'executor',
  AUDITOR = 'auditor',
  SUPER_ADMIN = 'super_admin',
}

export enum ScheduleType {
  REALTIME = 'REALTIME',
  DAILY = 'DAILY',
  CUSTOM = 'CUSTOM',
}

export enum ReportType {
  SUMMARY = 'SUMMARY',
  DETAIL = 'DETAIL',
  KPI = 'KPI',
}

export enum AudienceRole {
  APPROVER = 'APPROVER',
  IT = 'IT',
  AUDITOR = 'AUDITOR',
  OWNER = 'OWNER',
}

export enum ExternalTicketSystem {
  SERVICENOW = 'SERVICENOW',
  JIRA = 'JIRA',
}

export enum SourceApp {
  WEB = 'WEB',
  BOT = 'BOT',
  API = 'API',
  SCHEDULER = 'SCHEDULER',
}

export enum AuditEventType {
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_SUBMITTED = 'REQUEST_SUBMITTED',
  REQUEST_CANCELLED = 'REQUEST_CANCELLED',
  STAGE_ASSIGNED = 'STAGE_ASSIGNED',
  STAGE_APPROVED = 'STAGE_APPROVED',
  STAGE_REJECTED = 'STAGE_REJECTED',
  STAGE_REASSIGNED = 'STAGE_REASSIGNED',
  STAGE_ESCALATED = 'STAGE_ESCALATED',
  STAGE_TIMEOUT = 'STAGE_TIMEOUT',
  REMINDER_SENT = 'REMINDER_SENT',
  EXECUTION_STARTED = 'EXECUTION_STARTED',
  ACCESS_GRANTED = 'ACCESS_GRANTED',
  ACCESS_REVOKED = 'ACCESS_REVOKED',
  ACCESS_EXPIRED = 'ACCESS_EXPIRED',
  EXECUTION_FAILED = 'EXECUTION_FAILED',
  ROLLBACK_STARTED = 'ROLLBACK_STARTED',
  ROLLBACK_COMPLETED = 'ROLLBACK_COMPLETED',
  ROLLBACK_FAILED = 'ROLLBACK_FAILED',
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_UPDATED = 'TICKET_UPDATED',
  POLICY_CREATED = 'POLICY_CREATED',
  POLICY_UPDATED = 'POLICY_UPDATED',
  POLICY_DELETED = 'POLICY_DELETED',
  CONNECTOR_TESTED = 'CONNECTOR_TESTED',
  CONNECTOR_CONFIGURED = 'CONNECTOR_CONFIGURED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REVOKED = 'ROLE_REVOKED',
}

export enum WorkflowEvent {
  SUBMIT = 'SUBMIT',
  POLICY_EVALUATED = 'POLICY_EVALUATED',
  STAGE_APPROVED = 'STAGE_APPROVED',
  STAGE_REJECTED = 'STAGE_REJECTED',
  SLA_BREACHED = 'SLA_BREACHED',
  ESCALATION_ACCEPTED = 'ESCALATION_ACCEPTED',
  ESCALATION_REJECTED = 'ESCALATION_REJECTED',
  REQUESTER_CANCELLED = 'REQUESTER_CANCELLED',
  JOB_STARTED = 'JOB_STARTED',
  JOB_COMPLETED = 'JOB_COMPLETED',
  JOB_FAILED = 'JOB_FAILED',
  ACCESS_EXPIRED = 'ACCESS_EXPIRED',
  MANUAL_REVOKE = 'MANUAL_REVOKE',
  ROLLBACK_COMPLETED = 'ROLLBACK_COMPLETED',
  ROLLBACK_FAILED = 'ROLLBACK_FAILED',
}
